// Cyberpunk 13 cyberspace: shared constants.
// Split from cyberimp internals; keep gameplay logic out of organ item definitions.

#define NEURAL_INTERFACE_DEFAULT_ICE_STAT 2
#define NEURAL_INTERFACE_MIN_TIMER (5 SECONDS)
#define NEURAL_INTERFACE_BASE_TIMER (30 SECONDS)
#define NEURAL_INTERFACE_TIMER_STEP (5 SECONDS)
#define NEURAL_INTERFACE_HACKING_TIMER_STEP (10 SECONDS)
#define NEURAL_INTERFACE_MIN_GRID 5
#define NEURAL_INTERFACE_MAX_GRID 10
#define NEURAL_INTERFACE_MIN_SEQUENCE 3
#define NEURAL_INTERFACE_MAX_SEQUENCE 10
#define NEURAL_INTERFACE_BASE_RESERVE 6
#define NEURAL_INTERFACE_RESERVE_PER_LEVEL 3
#define NEURAL_INTERFACE_MAX_RESERVE 24
#define CYBER_ICE_MODEL_BASIC "basic"
#define CYBER_ICE_MODEL_MK2 "mk2"
#define CYBER_ICE_MODEL_CORPORATE "corporate"
#define CYBER_ICE_MODEL_IMPROVED "improved"
#define CYBERSPACE_NODE_MANUFACTURER_DIVERSITY_BONUS 0.05
#define NEURAL_INTERFACE_SELF_REPAIR_PER_SECOND 0.5
#define NEURAL_INTERFACE_SELF_REPAIR_PAIN_MULTIPLIER 0.5
#define CYBER_ICE_HEX_POOL_SIZE 12
#define CYBER_ICE_MAX_SEQUENCE_COUNT 6
#define CYBER_ICE_NOISE_ALARM_STEP 20
#define CYBER_ICE_HACKING_ALARM_REDUCTION 5
#define CYBER_ICE_HACKING_CHECK_ALARM_REDUCTION_DIVISOR 10
#define CYBER_ICE_HACKING_PERK_ALARM_REDUCTION 10
#define CYBERSPACE_SCALE_DIVISOR 1
#define CYBERSPACE_NODE_MAX_OBJECTS 64
#define CYBERSPACE_NODE_MERGE_RANGE 3
#define CYBERSPACE_NODE_CLEAR_RADIUS 12
#define CYBERSPACE_NODE_OBJECT_TRACE_LIMIT 0
#define ZTRAIT_CYBERSPACE "Cyberspace"
#define CYBERSPACE_LAYER_PADDING 2
#define CYBERSPACE_LAYER_MIN_SIZE 24
#define CYBERSPACE_LAYER_REFRESH_INTERVAL (10 SECONDS)
#define CYBERSPACE_AVATAR_SAFE_DISTANCE 10
#define CYBERSPACE_ENGRAM_SAFE_DISTANCE 30
#define CYBERSPACE_RETURN_TO_BODY_RANGE 7
#define CYBERSPACE_ENGRAM_PHYSICAL_RANGE 3
#define CYBERSPACE_AVATAR_HARD_DISTANCE_EXTRA 10
#define CYBERSPACE_AVATAR_STRAIN_MOVE_DELAY_MULTIPLIER 2
#define CYBERSPACE_ENGRAM_TRANSFER_BLOCK (300 SECONDS)
#define CYBERSPACE_AVATAR_CHECK_INTERVAL (4 SECONDS)
#define CYBERSPACE_PASSIVE_NET_DATA_INTERVAL (1 MINUTES)
#define CYBERSPACE_ENGRAM_FREE_TIME (5 MINUTES)
#define CYBERSPACE_FREE_ENGRAM_OUTSIDE_VEIL_DELAY_MULTIPLIER 2
#define CYBERSPACE_FREE_ENGRAM_VEIL_REPAIR 2
#define CYBERSPACE_FREE_ENGRAM_GROWTH_INTERVAL (30 MINUTES)
#define CYBERSPACE_FREE_ENGRAM_MAX_GROWTH_STAGE 3
#define CYBERSPACE_FREE_ENGRAM_STAGE_ONE_DELAY_MULTIPLIER 1.5
#define CYBERSPACE_FREE_ENGRAM_STAGE_THREE_POWER_MULTIPLIER 1.25
#define CYBERSPACE_IMPRINT_SENSOR_TAP_DURATION (10 SECONDS)
#define CYBERSPACE_DETECTION_SENSOR_RANGE 7
#define CYBERSPACE_BODY_RELAX_KNOCKDOWN (4 SECONDS)
#define CYBERSPACE_AVATAR_OVERHEAT_PER_TILE 2
#define CYBERSPACE_AVATAR_DISTANCE_GRACE_TICKS 2
#define CYBERSPACE_COLD_BODY_COOLING_TEMP (T0C + 5)
#define CYBERSPACE_COLD_BODY_OVERHEAT_DECAY 1
#define CYBERSPACE_ICE_BATH_OVERHEAT_DECAY 3
#define CYBERSPACE_ICE_BATH_CAPACITY 120
#define CYBERSPACE_ICE_BATH_MIN_ICE 5
#define CYBERSPACE_AVATAR_BRAIN_DAMAGE_CHANCE 10
#define CYBERSPACE_BASE_ATTACK_TIME (7 SECONDS)
#define CYBERSPACE_OPEN_CONNECTION_BASE_TIME (10 SECONDS)
#define CYBERSPACE_STEALTH_CONNECTION_BASE_TIME (7 SECONDS)
#define CYBERSPACE_CONNECTION_MIN_TIME (1 SECONDS)
#define CYBERSPACE_STEALTH_ALARM_CHANCE 30
#define CYBERSPACE_HACKING_ALARM_REDUCTION_PER_LEVEL 5
#define CYBERSPACE_NODE_SHUTDOWN_INTEGRITY_THRESHOLD 10
#define CYBERSPACE_NODE_EMP_INTEGRITY_THRESHOLD 40
#define CYBERSPACE_NODE_EMAG_INTEGRITY_THRESHOLD 70
#define CYBERSPACE_NET_DATA_DOOR_CAMERA 1
#define CYBERSPACE_NET_DATA_TERMINAL_SERVER 10
#define CYBERSPACE_NET_DATA_GENERIC_MIN 2
#define CYBERSPACE_NET_DATA_GENERIC_MAX 9
#define CYBERSPACE_VEIL_SIZE 5
#define CYBERSPACE_VEIL_STORAGE_COUNT 1
#define CYBERSPACE_VEIL_ALTERNATIVE_COUNT 2
#define CYBERSPACE_VEIL_RESPONSE_COUNT 1
#define CYBERSPACE_VEIL_RESPONSE_RANGE 7
#define CYBERSPACE_VEIL_RESPONSE_COOLDOWN (10 SECONDS)
#define CYBERSPACE_VEIL_FULL_RESPONSE_DISTANCE 50
#define CYBERSPACE_VEIL_MAX_ALTERNATIVES_PER_TARGET 2
#define CYBERSPACE_VEIL_HUNT_RANGE 12
#define CYBERSPACE_VEIL_HUNT_INTERVAL (0.6 SECONDS)
#define CYBERSPACE_VEIL_AVATAR_INTEGRITY 30
#define CYBERSPACE_VEIL_AVATAR_BRAIN_DAMAGE 90
#define CYBERSPACE_VEIL_DATA_VAULT_CHANCE 20
#define CYBERSPACE_VEIL_DATA_VAULT_MIN_NETWORK_DISTANCE 100
#define CYBERSPACE_VEIL_DATA_VAULT_ATTACK_DAMAGE 8
#define CYBERSPACE_VEIL_DATA_VAULT_BASE_INTEGRITY 100
#define CYBERSPACE_VEIL_DATA_VAULT_LEVEL_INTEGRITY 25
#define CYBERSPACE_VEIL_DATA_VAULT_BASE_GUARDS 2
#define CYBERSPACE_VEIL_DATA_VAULT_GUARDS_PER_LEVEL 2
#define CYBERSPACE_VEIL_DATA_VAULT_MAX_LEVEL 5
#define CYBERSPACE_VEIL_DATA_VAULT_CHARGE_PER_LEVEL 2
#define CYBERSPACE_VEIL_DATA_VAULT_GUARD_RANGE 7
#define CYBERSPACE_VEIL_DATA_VAULT_GUARD_COOLDOWN (8 SECONDS)
#define CYBERSPACE_VEIL_REWARD_KEY_LENGTH 15
#define CYBERSPACE_STORAGE_REWARD_POINTS 2
#define CYBERSPACE_MODE_AVATAR "avatar"
#define CYBERSPACE_MODE_ENGRAM "engram"
#define CYBERSPACE_MODE_IMPRINT "imprint"
#define CYBERSPACE_AVATAR_ALPHA 180
#define CYBERSPACE_ENGRAM_ALPHA 190
#define CYBERSPACE_IMPRINT_ALPHA 150

#define CYBER_DEMON_EFFECT_DAMAGE "damage"
#define CYBER_DEMON_EFFECT_BURN "burn"
#define CYBER_DEMON_EFFECT_ACID "acid"
#define CYBER_DEMON_EFFECT_TOX "tox"
#define CYBER_DEMON_EFFECT_OVERHEAT "overheat"
#define CYBER_DEMON_EFFECT_OVERHEAT_DELTA "overheat_delta"
#define CYBER_DEMON_EFFECT_ATTRIBUTE "attribute"
#define CYBER_DEMON_EFFECT_SKILL "skill"
#define CYBER_DEMON_EFFECT_MOVE_SPEED "move_speed"
#define CYBER_DEMON_EFFECT_INTERACTION_SPEED "interaction_speed"
#define CYBER_DEMON_EFFECT_BLIND "blind"
#define CYBER_DEMON_EFFECT_DEAF "deaf"
#define CYBER_DEMON_EFFECT_SILENCE "silence"
#define CYBER_DEMON_EFFECT_BLOCK_IMPLANTS "block_implants"
#define CYBER_DEMON_EFFECT_BLOCK_DEMONS "block_demons"
#define CYBER_DEMON_EFFECT_STAMINA "stamina"
#define CYBER_DEMON_EFFECT_PROTECTION "protection"
#define CYBER_DEMON_EFFECT_PREBUILT "prebuilt"
#define CYBER_DEMON_EFFECT_WALL "wall"
#define CYBER_DEMON_EFFECT_CRYPTOKEY "cryptokey"
#define CYBER_DEMON_EFFECT_MOVEMENT "movement"
#define CYBER_DEMON_EFFECT_CLOAK "cloak"
#define CYBER_DEMON_EFFECT_VANISH "vanish"
#define CYBER_DEMON_EFFECT_ENGRAM_STUN "engram_stun"
#define CYBER_DEMON_EFFECT_BUFF "buff"
#define CYBER_DEMON_EFFECT_DEBUFF "debuff"
#define CYBER_DEMON_EFFECT_EMP "emp"

#define CYBER_DEMON_SPECIAL_MASS "mass"
#define CYBER_DEMON_SPECIAL_SPREAD "spread"
#define CYBER_DEMON_SPECIAL_JUMP "jump"
#define CYBER_DEMON_SPECIAL_REPEAT "repeat"
#define CYBER_DEMON_SPECIAL_STEALTH "stealth"
#define CYBER_DEMON_SPECIAL_EMP "emp"
#define CYBER_DEMON_SPECIAL_EMP_LIGHT "emp_light"
#define CYBER_DEMON_SPECIAL_EMP_HEAVY "emp_heavy"

#define CYBER_DEMON_MAX_SPECIAL_EFFECTS 2
#define CYBER_DEMON_MAX_COMPILED_MEMORY 8
#define CYBER_DEMON_PREBUILT_MEMORY 3
#define CYBER_DEMON_DISK_MEMORY 12
#define CYBER_DECK_MIN_MEMORY 2
#define CYBER_DECK_MAX_MEMORY 12
#define CYBER_DECK_DEFAULT_MEMORY 6
#define CYBER_DECK_COMPILE_COOLDOWN (2 MINUTES)
#define CYBER_TERMINAL_COMPILE_COOLDOWN (1 MINUTES)
#define CYBER_DEMON_PHYSICAL_WORLD_MULTIPLIER 0.9
#define CYBER_DEMON_DEFAULT_PSYCHIC_DAMAGE 2
#define CYBER_DEMON_BASE_STAMINA_COST 10
#define CYBER_DEMON_DEFAULT_FREQUENCY 1
#define CYBER_DEMON_MAX_FREQUENCY 10
#define CYBER_DEMON_MAX_PERIODIC_TICKS 120
#define CYBER_DEMON_DEFAULT_ACTIVATION_DELAY 0
#define CYBER_DEMON_WALL_BUILD_TIME (30 SECONDS)
#define CYBER_DEMON_WALL_COOLDOWN (30 SECONDS)
#define CYBER_DEMON_CLOAK_DURATION (120 SECONDS)
#define CYBER_DEMON_CLOAK_COOLDOWN (240 SECONDS)
#define CYBER_DEMON_CLOAK_ALPHA 25
#define CYBER_DEMON_VANISH_DURATION (30 SECONDS)
#define CYBER_DEMON_VANISH_COOLDOWN (300 SECONDS)
#define CYBER_DEMON_VANISH_ALPHA 0
#define CYBER_DEMON_CAMERA_GLITCH_RANGE 7
#define CYBER_DEMON_CAMERA_GLITCH_DURATION (5 SECONDS)
#define CYBER_DEMON_SOULCATCHER_DURATION (120 SECONDS)
#define CYBER_DEMON_SOULCATCHER_COOLDOWN (90 SECONDS)
#define CYBER_DEMON_SOULCONDUIT_DURATION (30 SECONDS)
#define CYBER_DEMON_SOULCONDUIT_COOLDOWN (600 SECONDS)
#define CYBER_DEMON_SPECIAL_SECONDARY_MULTIPLIER 0.5
#define CYBER_DEMON_SPECIAL_MASS_RANGE 1
#define CYBER_DEMON_SPECIAL_MASS_LIMIT 4
#define CYBER_DEMON_SPECIAL_SPREAD_RANGE 3
#define CYBER_DEMON_SPECIAL_JUMP_RANGE 3
#define CYBER_DEMON_SPECIAL_JUMP_LIMIT 2
#define CYBER_DEMON_SPECIAL_REPEAT_LIMIT 2
#define CYBER_DEMON_SPECIAL_SPREAD_DELAY (1 SECONDS)
