// Cyberpunk 13 cyberspace: shared constants.
// Split from cyberimp internals; keep gameplay logic out of organ item definitions.

#define NEURAL_INTERFACE_DEFAULT_ICE_STAT 2
#define NEURAL_INTERFACE_MIN_TIMER (5 SECONDS)
#define NEURAL_INTERFACE_BASE_TIMER (30 SECONDS)
#define NEURAL_INTERFACE_TIMER_STEP (5 SECONDS)
#define NEURAL_INTERFACE_HACKING_TIMER_STEP (10 SECONDS)
#define NEURAL_INTERFACE_MIN_GRID 5
#define NEURAL_INTERFACE_MAX_GRID 10
#define NEURAL_INTERFACE_MIN_SEQUENCE 3
#define NEURAL_INTERFACE_MAX_SEQUENCE 10
#define NEURAL_INTERFACE_BASE_RESERVE 6
#define NEURAL_INTERFACE_RESERVE_PER_LEVEL 3
#define NEURAL_INTERFACE_MAX_RESERVE 15
#define NEURAL_INTERFACE_SELF_REPAIR_PER_SECOND 0.5
#define NEURAL_INTERFACE_SELF_REPAIR_PAIN_MULTIPLIER 0.5
#define CYBER_ICE_HEX_POOL_SIZE 12
#define CYBER_ICE_MAX_SEQUENCE_COUNT 6
#define CYBER_ICE_NOISE_ALARM_STEP 20
#define CYBER_ICE_HACKING_ALARM_REDUCTION 5
#define CYBER_ICE_HACKING_CHECK_ALARM_REDUCTION_DIVISOR 10
#define CYBER_ICE_HACKING_PERK_ALARM_REDUCTION 10
#define CYBERSPACE_SCALE_DIVISOR 3
#define CYBERSPACE_NODE_MAX_OBJECTS 64
#define CYBERSPACE_NODE_MERGE_RANGE 3
#define CYBERSPACE_LAYER_MIN_SIZE 24
#define CYBERSPACE_LAYER_MAX_SIZE 64
#define CYBERSPACE_AVATAR_SAFE_DISTANCE 5
#define CYBERSPACE_ENGRAM_SAFE_DISTANCE 25
#define CYBERSPACE_AVATAR_CHECK_INTERVAL (2 SECONDS)
#define CYBERSPACE_AVATAR_OVERHEAT_PER_TILE 2
#define CYBERSPACE_AVATAR_BRAIN_DAMAGE_CHANCE 10
#define CYBERSPACE_NET_DATA_DOOR_CAMERA 1
#define CYBERSPACE_NET_DATA_TERMINAL_SERVER 10
#define CYBERSPACE_NET_DATA_GENERIC_MIN 2
#define CYBERSPACE_NET_DATA_GENERIC_MAX 9
#define CYBERSPACE_VEIL_SIZE 5
#define CYBERSPACE_VEIL_STORAGE_COUNT 1
#define CYBERSPACE_VEIL_ALTERNATIVE_COUNT 2
#define CYBERSPACE_STORAGE_REWARD_POINTS 2
#define CYBERSPACE_MODE_AVATAR "avatar"
#define CYBERSPACE_MODE_ENGRAM "engram"
#define CYBERSPACE_MODE_IMPRINT "imprint"
#define CYBERSPACE_AVATAR_ALPHA 180
#define CYBERSPACE_ENGRAM_ALPHA 190
#define CYBERSPACE_IMPRINT_ALPHA 150
