#define SKILL_XP_COOKING_PER_ITEM 12
#ifndef SKILL_XP_GARDENING_PER_HARVEST
#define SKILL_XP_GARDENING_PER_HARVEST 8
#endif
#ifndef SKILL_XP_GARDENING_PER_WATERING
#define SKILL_XP_GARDENING_PER_WATERING 3
#endif
#define SKILL_XP_ANALYSIS_PER_SCAN 6
