// CyberPunk NPC strategic layer. This extends the existing AI controller system;
// it is not a separate subsystem.

#define CY_NPC_ROLE_CIVILIAN "civilian"
#define CY_NPC_ROLE_DRONE "drone"
#define CY_NPC_ROLE_CORPORATE "corporate"
#define CY_NPC_ROLE_CORPORATE_WORKER "corporate_worker"
#define CY_NPC_ROLE_POLICE "police"
#define CY_NPC_ROLE_GOVERNMENT_WORKER "government_worker"
#define CY_NPC_ROLE_COURIER "courier"
#define CY_NPC_ROLE_BANDIT "bandit"
#define CY_NPC_ROLE_HOSTILE_ANIMAL "hostile_animal"
#define CY_NPC_ROLE_ANIMAL "animal"
#define CY_NPC_ROLE_REPAIR_DRONE "repair_drone"
#define CY_NPC_ROLE_MEDICAL_DRONE "medical_drone"

#define CY_NPC_STATE_CALM "calm"
#define CY_NPC_STATE_WORKING "working"
#define CY_NPC_STATE_ALERT "alert"
#define CY_NPC_STATE_COMBAT "combat"
#define CY_NPC_STATE_ORDERED "ordered"
#define CY_NPC_STATE_FLEEING "fleeing"
#define CY_NPC_STATE_PHANTOM "phantom"
#define CY_NPC_STATE_SEARCHING "searching"
#define CY_NPC_STATE_RETURNING "returning"
#define CY_NPC_STATE_DELIVERING "delivering"
#define CY_NPC_STATE_HELPING "helping"
#define CY_NPC_STATE_REPAIRING "repairing"
#define CY_NPC_STATE_RESTRAINING "restraining"

#define CY_NPC_LEVEL_PRIMITIVE 0
#define CY_NPC_LEVEL_BASIC 1
#define CY_NPC_LEVEL_TRAINED 2
#define CY_NPC_LEVEL_PROFESSIONAL 3
#define CY_NPC_LEVEL_ELITE 4
#define CY_NPC_LEVEL_SPECIAL 5

#define CY_NPC_CAP_HANDS (1<<0)
#define CY_NPC_CAP_INVENTORY (1<<1)
#define CY_NPC_CAP_MELEE (1<<2)
#define CY_NPC_CAP_RANGED (1<<3)
#define CY_NPC_CAP_GRAB (1<<4)
#define CY_NPC_CAP_RESTRAIN (1<<5)
#define CY_NPC_CAP_CARRY (1<<6)
#define CY_NPC_CAP_COVER (1<<7)
#define CY_NPC_CAP_AIM (1<<8)
#define CY_NPC_CAP_ITEM_USE (1<<9)
#define CY_NPC_CAP_SIGNAL (1<<10)
#define CY_NPC_CAP_DRONE (1<<11)
#define CY_NPC_CAP_MEDICAL (1<<12)
#define CY_NPC_CAP_REPAIR (1<<13)
#define CY_NPC_CAP_DELIVERY (1<<14)
#define CY_NPC_CAP_DEMONS (1<<15)
#define CY_NPC_CAP_IMPLANTS (1<<16)
#define CY_NPC_CAP_GROUP (1<<17)
#define CY_NPC_CAP_PHANTOM (1<<18)
#define CY_NPC_CAP_SCHEDULE (1<<19)
#define CY_NPC_CAP_LAW (1<<20)
#define CY_NPC_CAP_SOCIAL (1<<21)
#define CY_NPC_CAP_EQUIPMENT (1<<22)
#define CY_NPC_CAP_STEALTH (1<<23)

#define CY_NPC_ORDER_IDLE "idle"
#define CY_NPC_ORDER_MOVE "move"
#define CY_NPC_ORDER_WAIT "wait"
#define CY_NPC_ORDER_PATROL "patrol"
#define CY_NPC_ORDER_WORK "work"
#define CY_NPC_ORDER_GUARD "guard"
#define CY_NPC_ORDER_ATTACK "attack"
#define CY_NPC_ORDER_FLEE "flee"
#define CY_NPC_ORDER_CAPTURE "capture"
#define CY_NPC_ORDER_RESTRAIN "restrain"
#define CY_NPC_ORDER_CARRY "carry"
#define CY_NPC_ORDER_DELIVER "deliver"
#define CY_NPC_ORDER_ESCORT "escort"
#define CY_NPC_ORDER_USE_OBJECT "use_object"
#define CY_NPC_ORDER_USE_ITEM "use_item"
#define CY_NPC_ORDER_SIGNAL "signal"
#define CY_NPC_ORDER_ABILITY "ability"
#define CY_NPC_ORDER_RETURN_HOME "return_home"
#define CY_NPC_ORDER_SEARCH "search"
#define CY_NPC_ORDER_HEAL "heal"
#define CY_NPC_ORDER_REPAIR "repair"
#define CY_NPC_ORDER_PICKUP "pickup"
#define CY_NPC_ORDER_DROP "drop"
#define CY_NPC_ORDER_EQUIP "equip"
#define CY_NPC_ORDER_HOLD_POSITION "hold_position"
#define CY_NPC_ORDER_TAKE_COVER "take_cover"
#define CY_NPC_ORDER_AIM "aim"
#define CY_NPC_ORDER_DISARM "disarm"

#define CY_NPC_ORDER_PENDING "pending"
#define CY_NPC_ORDER_RUNNING "running"
#define CY_NPC_ORDER_DONE "done"
#define CY_NPC_ORDER_FAILED "failed"

#define CY_NPC_REL_ALLY 100
#define CY_NPC_REL_NEUTRAL 0
#define CY_NPC_REL_ENEMY -100

#define BB_CY_NPC_PROFILE "BB_cy_npc_profile"
#define BB_CY_NPC_ROLE "BB_cy_npc_role"
#define BB_CY_NPC_STATE "BB_cy_npc_state"
#define BB_CY_NPC_LEVEL "BB_cy_npc_level"
#define BB_CY_NPC_FACTION "BB_cy_npc_faction"
#define BB_CY_NPC_ORDER "BB_cy_npc_order"
#define BB_CY_NPC_HOME "BB_cy_npc_home"
#define BB_CY_NPC_PATROL "BB_cy_npc_patrol"
#define BB_CY_NPC_WORK_TARGET "BB_cy_npc_work_target"
#define BB_CY_NPC_OWNER "BB_cy_npc_owner"
#define BB_CY_NPC_GROUP "BB_cy_npc_group"
#define BB_CY_NPC_LAST_SIGNAL "BB_cy_npc_last_signal"
#define BB_CY_NPC_SCHEDULE "BB_cy_npc_schedule"
#define BB_CY_NPC_CURRENT_PHASE "BB_cy_npc_current_phase"
#define BB_CY_NPC_THREAT "BB_cy_npc_threat"
#define BB_CY_NPC_SEARCH_CENTER "BB_cy_npc_search_center"
#define BB_CY_NPC_DELIVERY_TARGET "BB_cy_npc_delivery_target"
#define BB_CY_NPC_CARRY_TARGET "BB_cy_npc_carry_target"
#define BB_CY_NPC_ROLE_SLOT "BB_cy_npc_role_slot"
#define BB_CY_NPC_CONTRACT "BB_cy_npc_contract"
#define BB_CY_NPC_COVER_TARGET "BB_cy_npc_cover_target"
#define BB_CY_NPC_AIM_TARGET "BB_cy_npc_aim_target"
#define BB_CY_NPC_EVENT_MEMORY "BB_cy_npc_event_memory"
#define BB_CY_NPC_PHANTOM_INVENTORY "BB_cy_npc_phantom_inventory"

#define CY_NPC_EVENT_ATTACK "attack"
#define CY_NPC_EVENT_DAMAGE "damage"
#define CY_NPC_EVENT_CRIME "crime"
#define CY_NPC_EVENT_CONTRACT "contract"
#define CY_NPC_EVENT_ALARM "alarm"
