//CYBERPUNK CORPORATIONS - corporation-funded contract integration.

/datum/controller/subsystem/cyberpunk_corporations/proc/get_cyberpunk_corporate_contracts_ui(corporation_id)
	corporation_id = cyberpunk_normalize_corporation_id(corporation_id)
	var/list/contracts = list()
	for(var/contract_id in SSeconomy.cyberpunk_contracts)
		var/datum/cyberpunk_contract/contract = SSeconomy.cyberpunk_contracts[contract_id]
		if(contract?.source_corporation != corporation_id)
			continue
		contracts += list(contract.to_ui_data(null, FALSE))
	return contracts

/proc/pick_cyberpunk_generated_contract_item_type()
	var/static/list/t1_items = list(
		/obj/item/flashlight,
		/obj/item/radio,
		/obj/item/crowbar,
		/obj/item/wrench,
		/obj/item/screwdriver,
		/obj/item/multitool,
		/obj/item/healthanalyzer,
		/obj/item/stack/sheet/iron,
		/obj/item/stack/sheet/glass,
	)
	var/static/list/t2_items = list(
		/obj/item/crowbar/power,
		/obj/item/screwdriver/power,
		/obj/item/stack/sheet/plasteel,
		/obj/item/stack/sheet/mineral/plasma,
		/obj/item/healthanalyzer/advanced,
	)
	return prob(12) ? pick(t2_items) : pick(t1_items)

/datum/cyberpunk_corporation/proc/create_corporate_contract(contract_type = null)
	if(hidden)
		return null
	contract_type ||= pick(CYBERPUNK_CONTRACT_DELIVERY, CYBERPUNK_CONTRACT_REPAIR, CYBERPUNK_CONTRACT_BUILD, CYBERPUNK_CONTRACT_MINING, CYBERPUNK_CONTRACT_SABOTAGE)
	var/target = "work order"
	var/description = "Corporate work order."
	var/required_amount = 1
	var/required_percent = 75
	switch(contract_type)
		if(CYBERPUNK_CONTRACT_DELIVERY)
			var/obj/item/generated_item = pick_cyberpunk_generated_contract_item_type()
			target = initial(generated_item.name)
			var/generated_tier = get_cyberpunk_item_tier_for_type(generated_item)
			description = "Deliver the requested T[generated_tier] cargo to the corporate representative."
		if(CYBERPUNK_CONTRACT_REPAIR)
			target = pick("door", "machine", "terminal", "generator")
			description = "Restore the target above the required integrity threshold."
			required_percent = rand(65, 90)
		if(CYBERPUNK_CONTRACT_BUILD)
			target = pick("barricade", "table", "window", "structure")
			description = "Build the requested structure in the assigned area."
		if(CYBERPUNK_CONTRACT_MINING)
			target = pick("ore", "glass", "metal", "plasma")
			description = "Submit the requested resource stack."
			required_amount = rand(3, 8)
		if(CYBERPUNK_CONTRACT_SABOTAGE)
			target = pick("door", "camera", "terminal", "machine")
			description = "Damage or disable the target to the required threshold."
			required_percent = rand(0, 40)

	var/payment = rand(150, 650)
	if(!charge_funds(payment, "corporate contract escrow"))
		add_history("failed to fund corporate contract: insufficient budget")
		return null

	var/datum/cyberpunk_contract/contract = new
	contract.id = SSeconomy.next_cyberpunk_contract_id++
	contract.title = "[name] contract #[contract.id]"
	contract.description = description
	contract.contract_type = contract_type
	contract.target_text = target
	contract.creator_name = name
	contract.creator_character_key = "corp:[id]"
	contract.creator_account_id = account_id
	contract.payment = payment
	contract.deposit = rand(0, 2) ? 0 : rand(25, 100)
	contract.penalty = rand(0, 2) ? 0 : rand(25, 100)
	contract.escrow_payment = payment
	contract.legal = TRUE
	contract.public_contract = TRUE
	contract.source_corporation = id
	contract.required_amount = required_amount
	contract.required_percent = required_percent
	contract.direct_access_code = uppertext(random_string(8, GLOB.hex_characters))
	contract.due_time = world.time + rand(35, 90) MINUTES
	contract.created_at = world.time
	contract.setup_default_condition()
	contract.add_history("generated by [name]; [payment][MONEY_SYMBOL] reserved from corporate budget")
	SSeconomy.cyberpunk_contracts["[contract.id]"] = contract
	addtimer(CALLBACK(contract, TYPE_PROC_REF(/datum/cyberpunk_contract, timeout_check)), contract.due_time - world.time, TIMER_STOPPABLE)
	add_history("created corporate contract #[contract.id] for [payment][MONEY_SYMBOL]")
	return contract

/datum/cyberpunk_corporation/proc/create_service_outsource_contract(datum/cyberpunk_corporate_service_request/request)
	if(hidden || !request || request.status != CYBERPUNK_CORP_SERVICE_CREATED)
		return null
	var/payment = max(CYBERPUNK_CORP_OUTSOURCE_PAYMENT, round((request.cost || 0) * 1.5))
	if(!charge_funds(payment, "outsourced service escrow"))
		add_history("failed to outsource service request #[request.id]: insufficient budget")
		return null
	var/datum/cyberpunk_contract/contract = new
	contract.id = SSeconomy.next_cyberpunk_contract_id++
	contract.title = "[name] outsourced service #[request.id]"
	contract.description = "Complete or support corporate service '[request.service_label || request.service_id]' for [request.customer_name]."
	contract.contract_type = CYBERPUNK_CONTRACT_GUARD
	contract.target_text = request.service_label || request.service_id
	contract.creator_name = name
	contract.creator_character_key = "corp:[id]"
	contract.creator_account_id = account_id
	contract.payment = payment
	contract.deposit = 0
	contract.penalty = round(payment * 0.25)
	contract.escrow_payment = payment
	contract.legal = TRUE
	contract.public_contract = TRUE
	contract.source_corporation = id
	contract.required_amount = 1
	contract.required_percent = 75
	contract.direct_access_code = uppertext(random_string(8, GLOB.hex_characters))
	contract.due_time = world.time + 45 MINUTES
	contract.created_at = world.time
	contract.setup_default_condition()
	contract.add_history("outsourced from corporate service request #[request.id]")
	SSeconomy.cyberpunk_contracts["[contract.id]"] = contract
	addtimer(CALLBACK(contract, TYPE_PROC_REF(/datum/cyberpunk_contract, timeout_check)), contract.due_time - world.time, TIMER_STOPPABLE)
	request.add_history("outsourced as contract #[contract.id]")
	add_history("outsourced service request #[request.id] as contract #[contract.id]")
	return contract
