#define LIGHTWEIGHT_ATMOS_MAX_CLOUDS 600

#define LIGHTWEIGHT_ATMOS_CLOUD_FLOOR 0.5
#define LIGHTWEIGHT_ATMOS_TILE_CAPACITY 100
#define LIGHTWEIGHT_ATMOS_PRESSURE_SPREAD_THRESHOLD 0.65
#define LIGHTWEIGHT_ATMOS_OUTDOOR_DECAY_MULTIPLIER 4
#define LIGHTWEIGHT_ATMOS_VENT_FLOW_WEIGHT 4
#define LIGHTWEIGHT_ATMOS_PRESSURE_HAZARD_EXPIRE 2 SECONDS

#define GAS_DENSITY_LIGHT    -1
#define GAS_DENSITY_NEUTRAL   0
#define GAS_DENSITY_HEAVY     1

#define GAS_FILTER_PARTICLE  "particle"
#define GAS_FILTER_TOXIC     "toxic"
#define GAS_FILTER_CO2       "co2"
#define GAS_FILTER_N2O       "n2o"
#define GAS_FILTER_CHEMICAL  "chemical"
#define GAS_FILTER_HEAT      "heat"
#define GAS_FILTER_COLD      "cold"
#define GAS_FILTER_ACID      "acid"
#define GAS_FILTER_ANY       "any"

#define CLOUD_ALARM_NONE            0
#define CLOUD_ALARM_TOXIC          (1<<0)
#define CLOUD_ALARM_FIRE           (1<<1)
#define CLOUD_ALARM_COLD           (1<<2)
#define CLOUD_ALARM_ACID           (1<<3)
#define CLOUD_ALARM_CHEMICAL       (1<<4)
#define CLOUD_ALARM_SMOKE          (1<<5)
#define CLOUD_ALARM_OXYGEN_DANGER  (1<<6)
#define CLOUD_ALARM_BIOHAZARD      (1<<7)

#define COMSIG_AREA_CLOUD_ALARM "area_cloud_alarm"
#define COMSIG_AREA_CLOUD_CLEARED "area_cloud_cleared"

#define LIGHTWEIGHT_ATMOS_VENT_SCRUB_RATE 2

#define LIGHTWEIGHT_ATMOS_ALARM_THRESHOLD 8

#define LIGHTWEIGHT_ATMOS_CHEM_BREATH_FRACTION 0.05
#define LIGHTWEIGHT_ATMOS_CHEM_TOUCH_FRACTION 0.03

#define TRAIT_OUTDOOR_AIR "outdoor_air"

#define AREA_AIR_O2_DEFAULT 1.0
#define AREA_AIR_O2_TIGHT 0.6
#define AREA_AIR_O2_SUFFOCATING 0.3
#define AREA_AIR_O2_LETHAL 0.1

#define AREA_AIR_CO2_DEFAULT 0.0
#define AREA_AIR_CO2_TIGHT 0.4
#define AREA_AIR_CO2_TOXIC 0.7

#define AREA_AIR_O2_PER_BREATH 0.000075
#define AREA_AIR_CO2_PER_BREATH 0.000075
#define AREA_AIR_O2_PER_FIRE_POWER 0.002
#define AREA_AIR_CO2_PER_FIRE_POWER 0.0015

#define AREA_AIR_VENT_REFILL 0.06
#define AREA_AIR_VENT_SCRUB_CO2 0.05

#define AREA_AIR_OUTDOOR_REGEN 0.5
#define AREA_AIR_INDOOR_DRIFT 0.0005

#define AREA_AIR_TICK_INTERVAL 5

#define AREA_AIR_QUALITY_GOOD 0
#define AREA_AIR_QUALITY_TIGHT 1
#define AREA_AIR_QUALITY_SUFFOCATING 2
#define AREA_AIR_QUALITY_LETHAL 3
#define AREA_AIR_QUALITY_TOXIC 4

#define GAS_EFFECT_PER_TICK_MAX 50

#define BREATHES_UNDERWATER (1<<29)

#define TRAIT_INTERNAL_BREATHER "internal_breather"
#define TRAIT_HOLDING_BREATH "holding_breath"

#define BREATH_ENV_NORMAL    "normal"
#define BREATH_ENV_VACUUM    "vacuum"
#define BREATH_ENV_WATER     "water"
#define BREATH_ENV_INTERNALS "internals"

#define HOLDING_BREATH_DEFAULT_SECONDS 30

#define TANK_DEFAULT_BREATH_CAPACITY 100
