/// Cyberpunk city role groups.
#define CY_ROLE_GROUP_RESIDENT "resident"
#define CY_ROLE_GROUP_CORPORATE "corporate"
#define CY_ROLE_GROUP_OUTSOURCER "outsourcer"
#define CY_ROLE_GROUP_ANTAGONIST "antagonist"

/// City role flags. These describe what the role is allowed to manage in city-core systems.
#define CY_ROLE_FLAG_NONE 0
#define CY_ROLE_FLAG_BUSINESS_OWNER (1<<0)
#define CY_ROLE_FLAG_GOVERNMENT_OFFICIAL (1<<1)
#define CY_ROLE_FLAG_POLICE (1<<2)
#define CY_ROLE_FLAG_COUNCIL (1<<3)
#define CY_ROLE_FLAG_CORPORATE_TRAINEE (1<<4)
#define CY_ROLE_FLAG_CORPORATE_AGENT (1<<5)
#define CY_ROLE_FLAG_CORPORATE_SPECIALIST (1<<6)
#define CY_ROLE_FLAG_CORPORATE_REPRESENTATIVE (1<<7)
#define CY_ROLE_FLAG_OUTSOURCER (1<<8)
#define CY_ROLE_FLAG_BOUNTY_HUNTER (1<<9)
#define CY_ROLE_FLAG_MINOR_CRIMINAL (1<<10)
#define CY_ROLE_FLAG_MAJOR_CRIMINAL (1<<11)
#define CY_ROLE_FLAG_MONSTER (1<<12)

/// Cyberpunk role departments for preference grouping.
#define DEPARTMENT_CY_RESIDENTS "Residents"
#define DEPARTMENT_BITFLAG_CY_RESIDENTS (1<<12)
#define DEPARTMENT_CY_CORPORATE "Corporates"
#define DEPARTMENT_BITFLAG_CY_CORPORATE (1<<13)
#define DEPARTMENT_CY_OUTSOURCERS "Outsourcers"
#define DEPARTMENT_BITFLAG_CY_OUTSOURCERS (1<<14)
#define DEPARTMENT_CY_ANTAGONISTS "Antagonists"
#define DEPARTMENT_BITFLAG_CY_ANTAGONISTS (1<<15)

/// Cyberpunk role titles. Keep these stable: prefs, bans and statistics use the English keys.
#define JOB_CY_BUSINESS_OWNER "Business Owner"
#define JOB_CY_OFFICIAL "City Official"
#define JOB_CY_OFFICER "City Officer"
#define JOB_CY_COUNCIL_MEMBER "Council Member"

#define JOB_CY_CORPORATE_TRAINEE "Corporate Trainee"
#define JOB_CY_BEN_AGENT "Ben Agent"
#define JOB_CY_RYAZNOV_AGENT "Ryaznov Agent"
#define JOB_CY_STARLIGHT_AGENT "Starlight Agent"
#define JOB_CY_BEN_REAPER "Ben Reaper"
#define JOB_CY_RYAZNOV_ENGINEER "Ryaznov Engineer"
#define JOB_CY_STARLIGHT_LOGISTICIAN "Starlight Logistician"
#define JOB_CY_BEN_REPRESENTATIVE "Ben Representative"
#define JOB_CY_RYAZNOV_REPRESENTATIVE "Ryaznov Representative"
#define JOB_CY_STARLIGHT_REPRESENTATIVE "Starlight Representative"

#define JOB_CY_MERCENARY "Mercenary"
#define JOB_CY_LABORER "Laborer"

#define JOB_CY_STREET_THUG "Street Thug"
#define JOB_CY_GANG_MEMBER "Gang Member"
#define JOB_CY_ANARCHIST "Anarchist"
#define JOB_CY_MUTANT "Mutant"
#define JOB_CY_CONSTRUCT "Construct"
#define JOB_CY_SWARM "Swarm"
#define JOB_CY_SALVATION_ARMY "Salvation Army"

#define JOB_DISPLAY_ORDER_CY_BUSINESS_OWNER 101
#define JOB_DISPLAY_ORDER_CY_OFFICIAL 102
#define JOB_DISPLAY_ORDER_CY_OFFICER 103
#define JOB_DISPLAY_ORDER_CY_COUNCIL_MEMBER 104
#define JOB_DISPLAY_ORDER_CY_CORPORATE_TRAINEE 111
#define JOB_DISPLAY_ORDER_CY_BEN_AGENT 112
#define JOB_DISPLAY_ORDER_CY_RYAZNOV_AGENT 113
#define JOB_DISPLAY_ORDER_CY_STARLIGHT_AGENT 114
#define JOB_DISPLAY_ORDER_CY_BEN_REAPER 115
#define JOB_DISPLAY_ORDER_CY_RYAZNOV_ENGINEER 116
#define JOB_DISPLAY_ORDER_CY_STARLIGHT_LOGISTICIAN 117
#define JOB_DISPLAY_ORDER_CY_BEN_REPRESENTATIVE 118
#define JOB_DISPLAY_ORDER_CY_RYAZNOV_REPRESENTATIVE 119
#define JOB_DISPLAY_ORDER_CY_STARLIGHT_REPRESENTATIVE 120
#define JOB_DISPLAY_ORDER_CY_MERCENARY 131
#define JOB_DISPLAY_ORDER_CY_LABORER 132
#define JOB_DISPLAY_ORDER_CY_STREET_THUG 141
#define JOB_DISPLAY_ORDER_CY_GANG_MEMBER 142
#define JOB_DISPLAY_ORDER_CY_ANARCHIST 143
#define JOB_DISPLAY_ORDER_CY_MUTANT 144
#define JOB_DISPLAY_ORDER_CY_CONSTRUCT 145
#define JOB_DISPLAY_ORDER_CY_SWARM 146
#define JOB_DISPLAY_ORDER_CY_SALVATION_ARMY 147
