// living_flags
/// Simple mob trait, indicating it may follow continuous move actions controlled by code instead of by user input.
#define MOVES_ON_ITS_OWN (1<<0)
/// Always does *deathgasp when they die
/// If unset mobs will only deathgasp if supplied a death sound or custom death message
#define ALWAYS_DEATHGASP (1<<1)
/**
 * For carbons, this stops bodypart overlays being added to bodyparts from calling mob.update_body_parts().
 * This is useful for situations like initialization or species changes, where
 * update_body_parts() is going to be called ONE time once everything is done.
 */
#define STOP_OVERLAY_UPDATE_BODY_PARTS (1<<2)
/// Nutrition changed last life tick, so we should bulk update this tick
#define QUEUE_NUTRITION_UPDATE (1<<3)
/// Blood volume or status has changed since the last [proc/update_blood_effects] call.
/// Nowhere near guaranteed to happen only once per life tick, or at all.
#define BLOOD_UPDATE_QUEUED (1<<4)
/// This mob can have blood, cached value of [proc/can_have_blood]
#define LIVING_CAN_HAVE_BLOOD (1<<5)

/// Getter for a mob/living's lying angle, otherwise protected
#define GET_LYING_ANGLE(mob) (UNLINT(mob.lying_angle))
/// Checks if the mob can have blood
#define CAN_HAVE_BLOOD(mob) (mob.living_flags & LIVING_CAN_HAVE_BLOOD)
/// Queues a blood update for the next life tick for the mob
#define QUEUE_BLOOD_UPDATE(mob) mob.living_flags |= BLOOD_UPDATE_QUEUED

// Used in living mob offset list for determining pixel offsets
#define PIXEL_W_OFFSET "w"
#define PIXEL_X_OFFSET "x"
#define PIXEL_Y_OFFSET "y"
#define PIXEL_Z_OFFSET "z"

/// CyberPunk actor stat bounds.
#define CY_STAT_MINIMUM 1
#define CY_STAT_MAXIMUM 20
#define CY_STAT_DEFAULT 5

/// Check math from the character design block.
#define CY_STAT_VALUE_PER_POINT 5
#define CY_SKILL_VALUE_PER_LEVEL 10
#define CY_LUCK_PERCENT_PER_POINT 2.5

#define CY_CHECK_MINIMUM_CHANCE 1
#define CY_CHECK_MAXIMUM_CHANCE 99

#define CY_SKILL_MINIMUM_LEVEL 0
#define CY_SKILL_MAXIMUM_LEVEL 6
#define CY_SKILL_EXPERIENCE_PER_LEVEL 50

#define CY_SKILL_LEVEL_UNTRAINED 0
#define CY_SKILL_LEVEL_BEGINNER 1
#define CY_SKILL_LEVEL_SKILLED 2
#define CY_SKILL_LEVEL_TRAINED 3
#define CY_SKILL_LEVEL_EXPERT 4
#define CY_SKILL_LEVEL_PROFESSIONAL 5
#define CY_SKILL_LEVEL_MASTER 6

#define CY_EXPERIENCE_THRESHOLD_BASE 100
#define CY_EXPERIENCE_THRESHOLD_PER_LEVEL 50
#define CY_SKILL_AUTO_LEVEL_LIMIT 2
#define CY_SKILL_CHECK_EXPERIENCE_BASE 5
#define CY_SKILL_CHECK_EXPERIENCE_DIFFICULTY_DIVISOR 10
#define CY_SKILL_CHECK_EXPERIENCE_SUCCESS_MULTIPLIER 1
#define CY_SKILL_CHECK_EXPERIENCE_FAILURE_MULTIPLIER 0.5
#define CY_SKILL_EXPERIENCE_SHARE 0.75
#define CY_STAT_EXPERIENCE_SHARE 0.25
#define CY_AWAKE_TRAINING_EXPERIENCE_INTERVAL (5 MINUTES)
#define CY_AWAKE_TRAINING_EXPERIENCE_AMOUNT 1
#define CY_NEED_STAGE_LOW 1
#define CY_NEED_STAGE_CRITICAL 2
#define CY_NEED_STAGE_EMPTY 3
#define CY_MOOD_MINIMUM -15
#define CY_MOOD_MAXIMUM 15
#define CY_MOOD_STAT_STEP 5
#define CY_MOOD_NEGATIVE_SLOWDOWN_PER_STEP 0.25
#define CY_MOOD_POSITIVE_ACTIONSPEED_PER_STEP -0.15
#define CY_SKILL_PERK_CHECK_BONUS_PER_LEVEL 2
#define CY_SKILL_PERK_EXPERIENCE_BONUS_PER_LEVEL 5
#define CY_SKILL_PERK_WORK_SPEED_BONUS_PER_LEVEL 1
#define CY_SKILL_PERK_QUALITY_BONUS_PER_LEVEL 1
#define CY_CLEANING_BEAUTY_EXPERIENCE_ADJUSTMENT -15
#define CY_CLEANING_GENERIC_WASH_EXPERIENCE 1.5
#define CY_FISHING_DIFFICULTY_EXPERIENCE_MULTIPLIER 0.015
#define CY_FISHING_EXPERIENCE_PER_SECOND (CY_EXPERIENCE_THRESHOLD_BASE * 25 / (15 MINUTES * 0.1))
#define CY_MINING_BOULDER_SIZE_EXPERIENCE 10
#define CY_ATHLETICS_MISC_EXPERIENCE 5

#define CY_WEAPON_SKILL_DAMAGE_PER_LEVEL 0.10
#define CY_WEAPON_SKILL_COOLDOWN_PER_LEVEL 0.05
#define CY_WEAPON_SKILL_DEFENSE_BYPASS_PER_LEVEL 5
#define CY_WEAPON_SKILL_ACCURACY_PER_LEVEL 3
#define CY_WEAPON_SKILL_SPREAD_REDUCTION_PER_LEVEL 0.08
#define CY_WEAPON_SKILL_MELEE_EXPERIENCE_PER_DAMAGE 0.6
#define CY_WEAPON_SKILL_FIRE_EXPERIENCE 2
#define CY_PROFESSIONAL_SKILL_SPEED_PER_LEVEL 0.07
#define CY_PROFESSIONAL_SKILL_QUALITY_PER_LEVEL 0.25
#define CY_PROFESSIONAL_SKILL_EXPERIENCE_BASE 4
#define CY_PROFESSIONAL_SKILL_CRAFT_EXPERIENCE 8
#define CY_DRIVING_SKILL_SPEED_PER_LEVEL 0.04
#define CY_DRIVING_SKILL_EXPERIENCE_PER_MOVE 0.5
#define CY_MUSIC_SKILL_EXPERIENCE_PER_USE 3
#define CY_COHORT_BASE_LIMIT 1
#define CY_DEFAULT_FOV_DEGREES 180
#define CY_STEALTH_CHAMELEON_MAX 100
#define CY_STEALTH_LIGHT_PENALTY_MAX 45
#define CY_STEALTH_MOVE_PENALTY 15
#define CY_STEALTH_WEIGHT_PENALTY_PER_CLASS 4
#define CY_STEALTH_MIN_ALPHA 45
#define CY_STEALTH_MOVE_SLOWDOWN 0.6
#define CY_STEALTH_ATTACK_DAMAGE_BONUS 0.25

#define CY_STEALTH_WALL_OFFSET_SOURCE "cy_wall_press"
#define CY_STEALTH_WALL_PIXEL_OFFSET 10
#define CY_STEALTH_WALL_CHAMELEON_BONUS 25
#define CY_STEALTH_DEBUG_INTERVAL (1 SECONDS)
#define CY_STEALTH_HIDDEN_CHAMELEON_BONUS 40
#define CY_SPRINT_STAMINA_COST_PER_STEP 3
#define CY_SPRINT_STAMINA_STOP_LOSS 85
#define CY_SPRINT_SPEED_MODIFIER -0.5
#define CY_WRESTLING_RUN_DISTANCE 5
#define CY_WRESTLING_RUN_STEP_DELAY 1
#define CY_WRESTLING_RUN_DAMAGE 12
#define CY_WRESTLING_RUN_ELBOW_DAMAGE 18
#define CY_WRESTLING_RUN_ELBOW_KNOCKDOWN_CHANCE 60
#define CY_WRESTLING_RUN_KNOCKDOWN_TIME (3 SECONDS)
#define CY_PARKOUR_MODE_TIMEOUT (3 SECONDS)
#define CY_PARKOUR_JUMP_STAMINA_COST 8
#define CY_PARKOUR_CLIMB_STAMINA_COST 10
#define CY_PARKOUR_HANG_OFFSET_SOURCE "cy_parkour_hang"
#define CY_PARKOUR_HANG_PIXEL_OFFSET 12
#define CY_PARKOUR_SLIDE_FALL_CHANCE 25

#define CY_OUT_OF_FOV_DAMAGE_BONUS 0.20
#define CY_HEALTH_CRIT_THRESHOLD 0
#define CY_HEALTH_CLINICAL_DEATH_THRESHOLD -100
#define CY_HEALTH_FINAL_DEATH_THRESHOLD -200
#define CY_CLINICAL_ORGAN_DAMAGE_PER_SECOND 0.25
#define CY_IMPLANT_OVERHEAT_DECAY_PER_SECOND 1
#define CY_IMPLANT_OVERHEAT_PSYCHIC_PER_SECOND 0.1
#define CY_IMPLANT_OVERHEAT_PAIN_PER_SECOND 0.05
#define CY_IMPLANT_CORP_MISMATCH_OVERHEAT_MULTIPLIER 1.5
#define CY_IMPLANT_CORP_MISMATCH_FAILURE_MODIFIER 10
#define CY_DAEMON_CORP_MISMATCH_CAST_MULTIPLIER 1.35
#define CY_DAEMON_CORP_MISMATCH_EFFECTIVENESS_MULTIPLIER 0.75

// Skillchip categories are not part of the removed legacy skill subsystem.
#define SKILLCHIP_CATEGORY_GENERAL "general"
#define SKILLCHIP_CATEGORY_JOB "job"

// Cyberpunk character compatibility aliases used by older integration callsites.
#ifndef CY_MOOD_VALUE_PER_LEVEL
#define CY_MOOD_VALUE_PER_LEVEL CY_MOOD_STAT_STEP
#endif
#ifndef CY_MOOD_LUCK_PER_STEP
#define CY_MOOD_LUCK_PER_STEP 1
#endif
#ifndef CY_MOOD_NEGATIVE_SPEED_PER_STEP
#define CY_MOOD_NEGATIVE_SPEED_PER_STEP CY_MOOD_NEGATIVE_SLOWDOWN_PER_STEP
#endif
#ifndef CY_PAIN_THRESHOLD
#define CY_PAIN_THRESHOLD 200
#endif
#ifndef CY_PAIN_MOVESPEED_DIVISOR
#define CY_PAIN_MOVESPEED_DIVISOR 150
#endif
#ifndef CY_PAIN_ACTIONSPEED_DIVISOR
#define CY_PAIN_ACTIONSPEED_DIVISOR 200
#endif
#ifndef CY_PAIN_MAX_MOVESPEED_SLOWDOWN
#define CY_PAIN_MAX_MOVESPEED_SLOWDOWN 3
#endif
#ifndef CY_PAIN_MAX_ACTIONSPEED_SLOWDOWN
#define CY_PAIN_MAX_ACTIONSPEED_SLOWDOWN 2
#endif

// CYBERPUNK 13 STAGE 3 CORE MEDICAL DEFINES START
#define CY_ORGAN_CONDITION_CIRRHOSIS "cirrhosis"
#define CY_ORGAN_CONDITION_CARDIAC_ARREST "cardiac_arrest"
#define CY_ORGAN_CONDITION_LUNG_PUNCTURE "lung_puncture"
#define CY_ORGAN_CONDITION_STOMACH_POISONING "stomach_poisoning"
#define CY_ORGAN_CONDITION_BLINDNESS "blindness"
#define CY_ORGAN_CONDITION_DEAFNESS "deafness"
#define CY_ORGAN_CONDITION_TONGUE_NUMBNESS "tongue_numbness"
#define CY_ORGAN_CONDITION_BRAIN_TRAUMA "brain_trauma"

#define CY_REAGENT_ROUTE_BREATH "breath"
#define CY_REAGENT_ROUTE_INJECT "inject"
#define CY_REAGENT_ROUTE_INGEST "ingest"
#define CY_REAGENT_ROUTE_TOUCH "touch"

#define CY_BLOOD_OXYGENATION_BRAIN_REQUIRED 0.70
#define CY_LOW_OXYGEN_BRAIN_DAMAGE_PER_SECOND 0.20
#define CY_CRITICAL_OXYGEN_BRAIN_DAMAGE_PER_SECOND 0.65
#define CY_LUNG_PUNCTURE_EFFICIENCY_LOSS 0.25
#define CY_STIR_REACTION_STEP_MULTIPLIER 1.5
#define CY_STIR_HAND_EXPOSURE_VOLUME 0.35
#define CY_IMPLANT_BASE_ACTIVE_HEAT_PER_SECOND 1.35
#define CY_IMPLANT_BASE_PASSIVE_HEAT_PER_SECOND 0.15
#define CY_IMPLANT_NO_INTERFACE_FAILURE_CHANCE 2
#define CY_GENETIC_MAX_SEGMENTS 10
#define CY_HUMANITY_MONSTER_THRESHOLD 0
// CYBERPUNK 13 STAGE 3 CORE MEDICAL DEFINES END

// CYBERPUNK 13 STAGE 3 CORE MEDICAL FIX2 DEFINES START
#define CY_SURGERY_SKILL_MOD_ID "cy_medicine_skill"
#define CY_IMPLANT_ACTIVE_HEAT_SCALE 1.25
#define CY_IMPLANT_PASSIVE_HEAT_SCALE 0.25
#define CY_REAGENT_ROUTE_DEFAULT CY_REAGENT_ROUTE_INJECT
#define CY_GENETIC_MUTATION_MONSTER_RISK 15
#define CY_MEDICAL_EXAMINE_CLOSE_RANGE 1

// CYBERPUNK 13 STAGE 3 CORE MEDICAL FIX3 DEFINES START
#define CY_PRESSURE_EPINEPHRINE_BONUS 0.15
#define CY_PRESSURE_ATROPINE_BONUS 0.10
#define CY_LOW_OXYGEN_INTERACTION_SLOWDOWN 0.25
#define CY_HIGH_OXYGEN_STAMINA_RECOVERY 0.25
#define CY_FAST_BLOOD_LOSS_HEART_DAMAGE_PER_UNIT 0.04
#define CY_FAST_BLOOD_LOSS_BRAIN_DAMAGE_PER_UNIT 0.03
#define CY_TOXIN_LIVER_ROUTING_MULTIPLIER 0.75
#define CY_TOXIN_ORGAN_SPILLOVER_MULTIPLIER 0.35
#define CY_SURGERY_SELF_MIN_LEVEL CY_SKILL_LEVEL_EXPERT
#define CY_SURGERY_DIRTY_UNTRAINED_INFECTION_CHANCE 8
#define CY_SURGERY_THREAD_COST 0.1
#define CY_GENE_SEQUENCE_ROUND_SEED "cy_round_seed"
#define CY_GENE_SERUM_UNSTABLE_HUMANITY_DELTA -10
#define CY_IMPLANT_HUMANITY_HEAT_MULTIPLIER 0.01
#define CY_GENE_SEGMENT_HUMANITY_APPEARANCE "humanity_appearance"
#define CY_GENE_STABILIZER_RESTORE_PER_SECOND 1
#define CY_GENE_STABILIZER_DECAY_PER_SECOND 8
// CYBERPUNK 13 STAGE 3 CORE MEDICAL FIX3 DEFINES END
// CYBERPUNK 13 STAGE 3 CORE MEDICAL FIX2 DEFINES END
