#define CY_NETSPACE_SCALE 3
#define CY_NETSPACE_DEFAULT_WIDTH 120
#define CY_NETSPACE_DEFAULT_HEIGHT 120

#define CY_NET_AVATAR_MIRROR "mirror"
#define CY_NET_AVATAR_ACTIVE "active"
#define CY_NET_AVATAR_ENGRAM "engram"
#define CY_NET_AVATAR_ALTERNATIVE "alternative"

#define CY_NET_NODE_GENERIC "generic"
#define CY_NET_NODE_DOOR "door"
#define CY_NET_NODE_CAMERA "camera"
#define CY_NET_NODE_TERMINAL "terminal"
#define CY_NET_NODE_VENDING "vending"
#define CY_NET_NODE_TURRET "turret"
#define CY_NET_NODE_IMPLANT "implant"
#define CY_NET_NODE_AREA "area"

#define CY_NET_ACCESS_VIEW (1<<0)
#define CY_NET_ACCESS_USE (1<<1)
#define CY_NET_ACCESS_CONTROL (1<<2)
#define CY_NET_ACCESS_CONFIG (1<<3)
#define CY_NET_ACCESS_SUBNODES (1<<4)
#define CY_NET_ACCESS_ADMIN (CY_NET_ACCESS_VIEW|CY_NET_ACCESS_USE|CY_NET_ACCESS_CONTROL|CY_NET_ACCESS_CONFIG|CY_NET_ACCESS_SUBNODES)

#define CY_NET_SECURITY_OPEN 0
#define CY_NET_SECURITY_BASIC 25
#define CY_NET_SECURITY_CORPORATE 50
#define CY_NET_SECURITY_HARDENED 75
#define CY_NET_SECURITY_BLACKICE 100

#define CY_NET_TRACE_LOW 25
#define CY_NET_TRACE_ALARM 50
#define CY_NET_TRACE_REVEAL 75
#define CY_NET_TRACE_BURN 100

#define CY_NET_DISTANCE_SAFE 5
#define CY_NET_DISTANCE_BRAIN_BURN 6
#define CY_NET_ENGRAM_SAFE_DISTANCE 25

#define CY_NET_WALL_MAX_INTEGRITY 100
#define CY_NET_WALL_BUILD_RATE 10
#define CY_NET_WALL_ATTACK_DAMAGE 10

#define CY_NET_DAMAGE_ATTACK "attack"
#define CY_NET_DAMAGE_BREACH "breach"
#define CY_NET_DAMAGE_CONTROL "control"
#define CY_NET_DAMAGE_SYSTEM "system"

#define CY_NET_COLOR_ENGRAM "#31ff6a"
#define CY_NET_COLOR_ACTIVE "#3aa7ff"
#define CY_NET_COLOR_ALTERNATIVE "#ff3030"
#define CY_NET_COLOR_MIRROR "#7eeeff"

#ifndef CY_NETSPACE_FLOOR_RADIUS
#define CY_NETSPACE_FLOOR_RADIUS 7
#endif
#ifndef CY_NETSPACE_NODE_REGISTER_BUDGET
#define CY_NETSPACE_NODE_REGISTER_BUDGET 24
#endif
#ifndef CY_NETSPACE_PREWARM_BUDGET
#define CY_NETSPACE_PREWARM_BUDGET 2
#endif
#ifndef CY_NETSPACE_PREWARM_RADIUS
#define CY_NETSPACE_PREWARM_RADIUS 8
#endif

#define CY_NET_CONNECT_DURATION 5 MINUTES
#define CY_NET_CONNECT_TIME 60 SECONDS
#define CY_NET_CONNECT_COMBAT_TIME 10 SECONDS
#define CY_NET_NODE_DATA_DEFAULT 15
#define CY_NET_NODE_DAMAGE_GLITCH 33
#define CY_NET_NODE_DAMAGE_EMI 66
#define CY_NET_NODE_DAMAGE_OFFLINE 100

#define CY_NET_COLOR_NODE_STABLE "#55aaff"
#define CY_NET_COLOR_NODE_CONNECTING "#7deaff"
#define CY_NET_COLOR_NODE_CONNECTED "#48ff7a"
#define CY_NET_COLOR_NODE_DAMAGED "#ffdd55"
#define CY_NET_COLOR_NODE_BROKEN "#ff4444"

#ifndef CY_NET_SECURITY_RECOVERY_DELAY
#define CY_NET_SECURITY_RECOVERY_DELAY 1 MINUTES
#endif
#ifndef CY_NET_INTEGRITY_RECOVERY_DELAY
#define CY_NET_INTEGRITY_RECOVERY_DELAY 2 MINUTES
#endif
#ifndef CY_NET_CLUSTER_ATTACK_MULTIPLIER
#define CY_NET_CLUSTER_ATTACK_MULTIPLIER 0.35
#endif
#ifndef CY_NETSPACE_LOBBY_NODE_REGISTER_BUDGET
#define CY_NETSPACE_LOBBY_NODE_REGISTER_BUDGET 2000
#endif
#ifndef CY_NETSPACE_LOBBY_FLOOR_BUDGET
#define CY_NETSPACE_LOBBY_FLOOR_BUDGET 25000
#endif


// Cyberpunk netspace TZ update compatibility aliases.
#ifndef CY_NET_DAMAGE_PSYCHIC
#define CY_NET_DAMAGE_PSYCHIC "psychic"
#endif
#ifndef CY_NET_ATTACK_FOCUSED
#define CY_NET_ATTACK_FOCUSED 30
#endif
#ifndef CY_NET_ATTACK_SMEAR_MIN
#define CY_NET_ATTACK_SMEAR_MIN 1
#endif
#ifndef CY_NET_SECURITY_REGEN_DELAY
#define CY_NET_SECURITY_REGEN_DELAY (2 MINUTES)
#endif
#ifndef CY_NET_SECURITY_REGEN_STEP_TIME
#define CY_NET_SECURITY_REGEN_STEP_TIME (5 SECONDS)
#endif
#ifndef CY_NET_SECURITY_REGEN_STEP_AMOUNT
#define CY_NET_SECURITY_REGEN_STEP_AMOUNT 10
#endif
#ifndef CY_NET_DAMAGE_REPAIR_DELAY
#define CY_NET_DAMAGE_REPAIR_DELAY (2 MINUTES)
#endif
#ifndef CY_NET_CLUSTER_COLOR_NORMAL
#define CY_NET_CLUSTER_COLOR_NORMAL "#55aaff"
#endif
#ifndef CY_NET_CLUSTER_COLOR_CONNECTED
#define CY_NET_CLUSTER_COLOR_CONNECTED "#48ff7a"
#endif
#ifndef CY_NET_CLUSTER_COLOR_DAMAGED
#define CY_NET_CLUSTER_COLOR_DAMAGED "#ffdd55"
#endif
#ifndef CY_NET_CLUSTER_COLOR_BROKEN
#define CY_NET_CLUSTER_COLOR_BROKEN "#ff4444"
#endif
#ifndef CY_NET_ANALOG_OUTSIDE_VEIL_DAMAGE
#define CY_NET_ANALOG_OUTSIDE_VEIL_DAMAGE 2
#endif
#ifndef CY_DEMON_MAX_COMPILED_MEMORY
#define CY_DEMON_MAX_COMPILED_MEMORY 8
#endif
#ifndef CY_DEMON_DISK_MEMORY
#define CY_DEMON_DISK_MEMORY 12
#endif
#ifndef CY_DEMON_SPECIAL_MAX
#define CY_DEMON_SPECIAL_MAX 2
#endif

#ifndef CY_NET_PROJECTION_SCAN_INTERVAL
#define CY_NET_PROJECTION_SCAN_INTERVAL (5 SECONDS)
#endif
#ifndef CY_NET_PROJECTION_IMPLANT_INTEGRITY
#define CY_NET_PROJECTION_IMPLANT_INTEGRITY 100
#endif
#ifndef CY_NET_ENGRAM_VEIL_UNBIND_TIME
#define CY_NET_ENGRAM_VEIL_UNBIND_TIME (5 MINUTES)
#endif
#ifndef CY_NET_ENGRAM_VEIL_REGEN
#define CY_NET_ENGRAM_VEIL_REGEN 2
#endif
#ifndef CY_NET_DETECTION_SENSOR_RANGE
#define CY_NET_DETECTION_SENSOR_RANGE 7
#endif
#ifndef CY_NET_DETECTION_MOVE_TRACE
#define CY_NET_DETECTION_MOVE_TRACE 1
#endif
#ifndef CY_NET_DETECTION_NEAR_TRACE
#define CY_NET_DETECTION_NEAR_TRACE 2
#endif
#ifndef CY_NET_DETECTION_REVEAL_TRACE
#define CY_NET_DETECTION_REVEAL_TRACE 75
#endif
#ifndef CY_NET_DETECTION_BURN_TRACE
#define CY_NET_DETECTION_BURN_TRACE 100
#endif
#ifndef CY_NET_DAMAGE_IMPLANT_EMI_THRESHOLD
#define CY_NET_DAMAGE_IMPLANT_EMI_THRESHOLD 0
#endif
