//CYBERPUNK BUSINESS - definitions moved out of account.dm for architecture clarity.
#define CYBERPUNK_BUSINESS_ACCESS_TERMINAL "terminal"
#define CYBERPUNK_BUSINESS_ACCESS_FINANCE "finance"
#define CYBERPUNK_BUSINESS_ACCESS_STOCK "stock"
#define CYBERPUNK_BUSINESS_ACCESS_STAFF "staff"
#define CYBERPUNK_BUSINESS_ACCESS_CONTRACTS "contracts"

#define CYBERPUNK_BUSINESS_EXTERNAL_UNIT_COST 10
#define CYBERPUNK_BUSINESS_TAX_RATE 0.05
#define CYBERPUNK_BUSINESS_AUTO_RESTOCK_INTERVAL (5 MINUTES)
