//CYBERPUNK CORPORATIONS - shared corporation defines.
#define CYBERPUNK_CORP_BENN "benn"
#define CYBERPUNK_CORP_RYAZNOV "ryaznov"
#define CYBERPUNK_CORP_STARLIGHT "starlight"
#define CYBERPUNK_CORP_GOVERNMENT "government"
#define CYBERPUNK_CORP_STARTING_BUDGET 15000
#define CYBERPUNK_CORP_RESEARCH_TO_CREDITS 50
#define CYBERPUNK_CORP_LEVEL_STEP 100
#define CYBERPUNK_CORP_TAX_RATE 0.03
#define CYBERPUNK_CORP_TECH_KEY_DOWNLOAD_TIME (60 SECONDS)
#define CYBERPUNK_CORP_TECH_KEY_DOWNLOAD_MIN_TIME (10 SECONDS)
#define CYBERPUNK_CORP_TECH_KEY_HACKING_STEP (8 SECONDS)
#define CYBERPUNK_CORP_REVERSE_PROGRESS 25
#define CYBERPUNK_CORP_REVERSE_BREAKTHROUGH_CHANCE 20
#define CYBERPUNK_CORP_RESEARCH_TO_FOREIGN_PROGRESS_COST 20
#define CYBERPUNK_DATA_PAYLOAD_TECHNOLOGY_KEY "technology_key"
