//CYBERPUNK CORPORATIONS - corporation-funded contract integration.

/datum/controller/subsystem/cyberpunk_corporations/proc/get_cyberpunk_corporate_contracts_ui(corporation_id)
	corporation_id = cyberpunk_normalize_corporation_id(corporation_id)
	var/list/contracts = list()
	for(var/contract_id in SSeconomy.cyberpunk_contracts)
		var/datum/cyberpunk_contract/contract = SSeconomy.cyberpunk_contracts[contract_id]
		if(contract?.pool_corporation != corporation_id)
			continue
		contracts += list(contract.to_ui_data(null, FALSE))
	return contracts

/datum/cyberpunk_corporation/proc/create_pool_contract(contract_type = null)
	if(hidden)
		return null
	contract_type ||= pick(CYBERPUNK_CONTRACT_DELIVERY, CYBERPUNK_CONTRACT_REPAIR, CYBERPUNK_CONTRACT_BUILD, CYBERPUNK_CONTRACT_MINING, CYBERPUNK_CONTRACT_SABOTAGE)
	var/target = "work order"
	var/description = "Corporate pool work order."
	var/required_amount = 1
	var/required_percent = 75
	switch(contract_type)
		if(CYBERPUNK_CONTRACT_DELIVERY)
			target = pick("sealed packet", "data disk", "medical crate", "machine component")
			description = "Deliver the marked cargo to the corporate representative."
		if(CYBERPUNK_CONTRACT_REPAIR)
			target = pick("door", "machine", "terminal", "generator")
			description = "Restore the target above the required integrity threshold."
			required_percent = rand(65, 90)
		if(CYBERPUNK_CONTRACT_BUILD)
			target = pick("barricade", "table", "window", "structure")
			description = "Build the requested structure in the assigned area."
		if(CYBERPUNK_CONTRACT_MINING)
			target = pick("ore", "glass", "metal", "plasma")
			description = "Submit the requested resource stack."
			required_amount = rand(3, 8)
		if(CYBERPUNK_CONTRACT_SABOTAGE)
			target = pick("door", "camera", "terminal", "machine")
			description = "Damage or disable the target to the required threshold."
			required_percent = rand(0, 40)

	var/payment = rand(150, 650)
	if(!charge_funds(payment, "contract pool escrow"))
		add_history("failed to fund pool contract: insufficient budget")
		return null

	var/datum/cyberpunk_contract/contract = new
	contract.id = SSeconomy.next_cyberpunk_contract_id++
	contract.title = "[name] pool job #[contract.id]"
	contract.description = description
	contract.contract_type = contract_type
	contract.target_text = target
	contract.creator_name = name
	contract.creator_character_key = "corp:[id]"
	contract.creator_account_id = account_id
	contract.payment = payment
	contract.deposit = rand(0, 2) ? 0 : rand(25, 100)
	contract.penalty = rand(0, 2) ? 0 : rand(25, 100)
	contract.escrow_payment = payment
	contract.legal = TRUE
	contract.public_contract = TRUE
	contract.pool_contract = TRUE
	contract.pool_corporation = id
	contract.generated_pool_contract = TRUE
	contract.required_amount = required_amount
	contract.required_percent = required_percent
	contract.direct_access_code = uppertext(random_string(8, GLOB.hex_characters))
	contract.due_time = world.time + rand(35, 90) MINUTES
	contract.created_at = world.time
	contract.setup_default_condition()
	contract.add_history("generated by [name] corporate pool; [payment][MONEY_SYMBOL] reserved from corporate budget")
	SSeconomy.cyberpunk_contracts["[contract.id]"] = contract
	addtimer(CALLBACK(contract, TYPE_PROC_REF(/datum/cyberpunk_contract, timeout_check)), contract.due_time - world.time, TIMER_STOPPABLE)
	add_history("created pool contract #[contract.id] for [payment][MONEY_SYMBOL]")
	return contract

