#define CPR_COOLDOWN_BASE (5 SECONDS)
#define CPR_COOLDOWN_CHIP (4 SECONDS)

#define CPR_ACTION_TIME_BASE (2 SECONDS)
#define CPR_ACTION_TIME_CHIP (1 SECONDS)

#define CPR_OXY_HEAL_BASE 3
#define CPR_OXY_HEAL_CHIP 5

#define CPR_STAMINA_COST_BASE 5
#define CPR_STAMINA_COST_CHIP 2

#define CPR_ORGAN_PRESERVE_BASE (2 SECONDS)
#define CPR_ORGAN_PRESERVE_CHIP (3 SECONDS)

#define CPR_EARLY_DECAY_STEP (10 SECONDS)

#define HAS_DOCTOR_CHIP(mob) (HAS_MIND_TRAIT(mob, TRAIT_ENTRAILS_READER))
